Add files via upload
MPolishchuk8/ksHubLoginTest pull request #1
Opened 2024-08-15 22:08 UTC by MPolishchuk8

Це навіть не 5 хвилин, чекаю коментарі)

2024-08-19 06:27 UTC, e-genov-ks commented
> Це навіть не 5 хвилин, чекаю коментарі)

в описі пул реквесту люди додають опис змін, щоб легше було розуміти, що саме в коді. Ти фактично місце з чатом сплутав )

2024-08-19 06:37 UTC, e-genov-ks requested changes

2024-08-19 06:37 UTC, e-genov-ks commented on README.md
чому цей файл потрапив в ПР ?

2024-08-19 06:37 UTC, e-genov-ks commented on src/main/java/org/example/Main.java
> +}
для чого цей файл ? Яка його відповідальність?

2024-08-19 06:37 UTC, e-genov-ks commented on pom.xml
> +</project>
додавай завжди newline, про це і гітхаб каже

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/BaseTest.java
> +    protected ProfilePage profilePage;
в чому сенс тримати ці речі в baseTest ? BaseTest - абстракція, а фронт/логін/профайл сторінки - це реалізація певна.

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/BaseTest.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver\\chrome\\chromedriver.exe");
в мене мак. як мені запустити цей код ? )

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/BaseTest.java
> +        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
в чому сенс цього wait ? для чого чекати аж 10 секунд? уяви, що в тебе 1000 тестів і кожен буде чекати по 10 секунд,...

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/ConfProperties.java
> +    }
в когось просто скопіпастив цей код. Ну ок, проговоримо його голосом ))))

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/LoginTest.java
> +        driver.manage().window().maximize();
чого тільки тут на весь екран? Чому попередні кроку без цього?

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/LoginTest.java
> +        loginPage.clickLoginBtn();
для чого двічі натискати кнопку логіна ?

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/LoginTest.java
> +    void loginTest() {
що саме тестує цей тест? по назві не зрозуміло

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/pages/FrontPage.java
> +        this.wait = new WebDriverWait(driver, Duration.ofSeconds(10));
знову ці 10 секунд, які були вже в basePage

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/pages/FrontPage.java
> +        PageFactory.initElements(driver, this);
просто задублював рядки

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/pages/LoginPage.java
> +    @FindBy(xpath = "//*[contains(text(), 'Продовжити')]")
а якщо буде англійська мова ?

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/pages/ProfilePage.java
> +/* package org.example.pages;
для чого лишати коментарі ?

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/java/org/example/pages/ProfilePage.java
> +    @FindBy(xpath = "//*[contains(@class, 'UserProfileContainer_subButton__loxWR')]")
це погана практика шукати елементи по цсс-класам

2024-08-19 06:37 UTC, e-genov-ks commented on src/test/resources/conf.properties
> +password = Test678test
хардкодити паролі в репозиторія - дуже не правильно, безпека за таке з'їсть

2024-08-19 06:37 UTC, e-genov-ks commented on target/test-classes/org/example/BaseTest.class
для чого це було комітити ? це артефакти білда, їх не має бути в коді

2024-08-19 06:55 UTC, e-genov-ks commented
ну і назва ПР не відповідає тому що в коді. В назві "Add files via upload"

2024-08-19 09:45 UTC, e-genov-ks requested changes

2024-08-19 09:45 UTC, e-genov-ks commented on pom.xml
> +        </dependency>
зрозумій для чого ця бібліотека

2024-08-19 09:45 UTC, e-genov-ks commented on src/test/java/org/example/BaseTest.java
> +    protected ProfilePage profilePage;
почитай про Single Responsibility.

2024-08-19 09:45 UTC, e-genov-ks commented on src/test/java/org/example/BaseTest.java
> +    }
в даному випадку все буде працювати, тільки коли в тебе 1 віконечко. Якщо їх декілька - буде помилка

2024-08-19 09:45 UTC, e-genov-ks commented on src/test/java/org/example/BaseTest.java
> +    }
чого цей код саме тут ? Це BaseTest, а це метод про певну реалізацію

2024-08-19 09:45 UTC, e-genov-ks commented on src/test/java/org/example/pages/ProfilePage.java
> +        this.wait = new WebDriverWait(driver, Duration.ofSeconds(10));
для вивчення https://www.selenium.dev/documentation/webdriver/waits/

2024-08-19 14:07 UTC, MPolishchuk8 commented on README.md
Вніс зміни

2024-08-19 14:07 UTC, MPolishchuk8 commented on src/main/java/org/example/Main.java
> +}
Directory main deleted

2024-08-19 14:07 UTC, MPolishchuk8 commented on pom.xml
> +</project>
Newline added

2024-08-19 14:08 UTC, MPolishchuk8 commented on src/test/java/org/example/LoginTest.java
> +        loginPage.clickLoginBtn();
Button name changed to NextBtn

2024-08-19 14:08 UTC, MPolishchuk8 commented on src/test/java/org/example/LoginTest.java
> +    void loginTest() {
Comment with an explanation added

2024-08-19 14:08 UTC, MPolishchuk8 commented on src/test/java/org/example/pages/FrontPage.java
> +        PageFactory.initElements(driver, this);
Removed extra line

2024-08-19 14:10 UTC, MPolishchuk8 commented on src/test/java/org/example/pages/LoginPage.java
> +    @FindBy(xpath = "//*[contains(text(), 'Продовжити')]")
Changed to find element by id with attribute data-testid for all elements

2024-08-19 14:10 UTC, MPolishchuk8 commented on src/test/java/org/example/pages/ProfilePage.java
> +/* package org.example.pages;
Deleted extra comments

2024-08-19 14:15 UTC, MPolishchuk8 commented on src/test/java/org/example/pages/ProfilePage.java
> +    @FindBy(xpath = "//*[contains(@class, 'UserProfileContainer_subButton__loxWR')]")
Changed to find by id

2024-08-19 18:55 UTC, MPolishchuk8 commented on src/test/resources/conf.properties
> +password = Test678test
login and password moved to Environment variables

2024-08-19 19:01 UTC, MPolishchuk8 commented on src/test/java/org/example/BaseTest.java
> +    protected ProfilePage profilePage;
Moved to LoginTest class

2024-08-19 19:09 UTC, MPolishchuk8 commented on target/test-classes/org/example/BaseTest.class
Added to .gitignore

2024-08-19 19:17 UTC, MPolishchuk8 commented on pom.xml
> +        </dependency>
This library used to interact with web browsers using Java programming language, it provides all necessary components for this goal .

2024-08-19 19:18 UTC, MPolishchuk8 commented on src/test/java/org/example/BaseTest.java
> +    protected ProfilePage profilePage;
Moved to LoginTest class

2024-08-19 21:00 UTC, MPolishchuk8 commented on src/test/java/org/example/ConfProperties.java
> +    }
All properties to be taken from Environment variables, file deleted.

2024-08-21 12:21 UTC, MPolishchuk8 commented on src/test/java/org/example/BaseTest.java
> +        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
Global timeout set Configuration.timeout = 2000;

2024-08-22 09:33 UTC, MPolishchuk8 commented on src/test/java/org/example/BaseTest.java
> +    }
Moved to MainPage

2024-08-22 20:16 UTC, MPolishchuk8 commented on src/test/java/org/example/BaseTest.java
> +    }
Moved to MainPage

2024-08-22 20:16 UTC, MPolishchuk8 commented on src/test/java/org/example/BaseTest.java
> +    }
Condition added

2024-08-23 08:37 UTC, MPolishchuk8 commented on src/test/java/org/example/BaseTest.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver\\chrome\\chromedriver.exe");
Використав WebDriverManager

2024-08-23 08:39 UTC, MPolishchuk8 commented on src/test/java/org/example/pages/FrontPage.java
> +        this.wait = new WebDriverWait(driver, Duration.ofSeconds(10));
Прибрав, глобальний таймаут прописаний

2024-08-23 08:47 UTC, MPolishchuk8 commented on src/test/java/org/example/BaseTest.java
> +    }
Додав перевірку вікон що відкриваються за ідентифікатором

2024-08-23 08:48 UTC, MPolishchuk8 commented on src/test/java/org/example/BaseTest.java
> +    }
Переніс в MainPage

2024-08-26 07:26 UTC, e-genov-ks requested changes

2024-08-26 07:26 UTC, e-genov-ks commented on src/test/java/org/example/LoginTest.java
> +    void loginTest() {
Це найгірше, що можна було зробити. Коментарі - це дуже погано :) метод має називатись правильно, а не коментарі дописуватись

2024-08-26 07:26 UTC, e-genov-ks commented on src/test/java/org/example/pages/LoginPage.java
> +                if ($(By.xpath("//*[@data-testid='login-input']")).exists()) break;
шо це за логіка така ? він перемикається на вікно і потім виходить...

2024-08-26 07:26 UTC, e-genov-ks commented on src/test/java/org/example/pages/MainPage.java
> +    }
цей код дублюється, був в LoginPage

2024-08-26 07:32 UTC, e-genov-ks requested changes

2024-08-26 07:32 UTC, e-genov-ks commented on src/test/java/org/example/pages/ProfilePage.java
> +    private SelenideElement userMenu = $x("//*[contains(@title, 'login')]");
краще замість contains використовувати equal , бо contains це не строгий пошук

2024-08-28 12:05 UTC, e-genov-ks requested changes

2024-08-28 12:05 UTC, e-genov-ks commented on src/test/java/org/example/pages/LoginPage.java
> +        String originalWindow = driver.getWindowHandle();
помилка тут :)

2024-09-02 18:10 UTC, e-genov-ks requested changes

2024-09-02 18:10 UTC, e-genov-ks commented on src/test/java/org/example/LoginTest.java
> +        }
Для чого в сліп інструкції трай-кетч ?

2024-09-03 08:23 UTC, MPolishchuk8 reviewed
Воно зроблено для перехоплення виключення переривання потоку під час виконання сліпу

2024-09-03 08:23 UTC, MPolishchuk8 commented on src/test/java/org/example/LoginTest.java
> +        }
Воно зроблено для перехоплення виключення переривання потоку під час виконання сліпу

2024-09-03 08:24 UTC, e-genov-ks reviewed
Запропонував рішення без try/catch, щоб це норм читалось

2024-09-03 08:24 UTC, e-genov-ks commented on src/test/java/org/example/LoginTest.java
> +    void assertLoginSuccessWithCorrectCredentials() {
```suggestion
    void assertLoginSuccessWithCorrectCredentials() throws InterruptedException {

```

2024-09-03 08:24 UTC, e-genov-ks commented on src/test/java/org/example/LoginTest.java
> +        }
```suggestion
        Thread.sleep(1000);
```

2024-09-03 08:53 UTC, e-genov-ks approved these changes

2024-09-03 08:57 UTC, merged